### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by patriknw** [akka/akka.github.com#410]
- [x] some more space in the table in the community page
- [x] in the docs page the Get Started vs the Reference Docs boxes should be more separated, perhaps a new heading above the boxes: **Documentation**, or remove the Getting Started heading and put that in a centered box that stands out from the others
- [x] the dependency tabs are small and it's difficult to select all text and copy (3-click on mac), could we add some kind of copy to clipboard button that shows up when tab is selected (mouse over?)
- [x] Shall we add **Try Akka** at the top, linking directly to the Quickstart page of the docs, similar to https://www.lagomframework.com/
- [x] Get Involved in the footer belongs more in the Contribute column, perhaps change place of Source Code and Get Involved
- [x] Shouldn't "Lightbend Professional Support" be visible on the front page or the footer?

**Comment by patriknw** [comment]
One more idea, we could have another tab in the dependencies tabs with **g8** (`sbt new`) commands. We can have different g8 templates for most popular modules (they can all live in akka-scala-seed.g8 in different branches).

Would be nice if those tabs are expanded if selected.

**Comment by johanandren** [comment]
1, 2, 5, 6 - agree, fixing these
3 maybe my soon to be pushed fix that puts a bit more text in those boxes helps with selection? (at least I didn't have any copy-pasta-problems when I tried)
4, good idea, created a separate ticket to track #411

Regarding the last comment: I think there is a high risk that we load the docs page with too much information, it's meant to lead the user into the docs rather than contain all the info you need. Isn't that a module-specific template instruction perfect to have to in the beginning of corresponding docs section rather?

**Comment by johanandren** [comment]
Oh, wait, 1 refers to the scaladex link table/list right?

**Comment by patriknw** [comment]
> Regarding the last comment: I think there is a high risk that we load the docs page with too much information, it's meant to lead the user into the docs rather than contain all the info you need. Isn't that a module-specific template instruction perfect to have to in the beginning of corresponding docs section rather?

All those dependencies belongs in the docs, but I see those tabs as quick reference/copy for those that know what they want.
